image: ubuntu:latest

stages:
  - build
  - test
  - deploy

deploy_job:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - echo "Deploying to Amazon Linux server..."
    - rsync -av --delete ./build/ ec2-user@54.221.157.175:~/html/
