stages:
  - deploy

deploy_job:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to Amazon Linux server..."
    - rsync -av -e "ssh -i /Users/mans/Downloads/playground.pem" --delete ./build/ ec2-user@54.221.157.175:/path/to/html/

